language: python
python:
  - "3.8"
install:
  - pip install -r requirements.txt
before_script:
  - python manage.py migrate
  - python manage.py collectstatic --noinput
script:
  - flake8 .
  - python manage.py test